### ISSUE TITLE
excessive dependencies

### ISSUE THREAD

**Issue by aaronpeikert** [annajenul/UBayFS#12]
Installing this package requires installing ~200 dependencies amounting to over 250Mb of disc space. This seems a bit much to be honest.
Maybe one could reconsider if these packages are all really required and not suggest:

- shiny
- caret
- ggplot2
- ggpubr
- rpart
- knitr

**Comment by annajenul** [comment]
Thank you for pointing us to this issue. We implemented the function build.UBaymodel such that the user can provide any arbitrary feature selector via a function argument (we added some examples to the documentation). This makes the package more flexible, and that the same time, we could remove 'caret', 'rpart', GSelection', and 'glmnet' from the required packages. 
Further, we moved 'knitr' to the suggested packages and replaced 'ggpubr' with the smaller 'gridExtra' package.
