### ISSUE TITLE
[paper] Introduce the term feature selection

### ISSUE THREAD

**Issue by aaronpeikert** [annajenul/UBayFS#18]
I think the paper is generally clearly written but since you also aim at novice users with the Shiny app etc. I think it makes sense to introduce the core problem you are trying to solve in more colloquial terms. ML researchers, of course, know what you mean, but even the term "feature" sometimes causes some confusion with old-school stats-trained people.

**Comment by annajenul** [comment]
Good point! We added a short feature selection description at the paper's beginning.
