### ISSUE TITLE
link to prebuilt vignettes

### ISSUE THREAD

**Issue by aaronpeikert** [annajenul/UBayFS#20]
I think it would be more userfriendly to link prebuild vignettes instead of the code. Maybe use https://r-universe.dev/ or even better `usethis::use_pkgdown_github_pages()`. You have invested so much in good documentation, it deserves to be seen (which requires it to be accessible).

**Comment by aaronpeikert** [comment]
related https://github.com/openjournals/joss-reviews/issues/4848

**Comment by annajenul** [comment]
Thanks a lot for your suggestion, very good point! We added documentation.
