### ISSUE TITLE
UBayFS::train very verbose

### ISSUE THREAD

**Issue by dhvalden** [annajenul/UBayFS#23]
The solution is to pass `monitor=FALSE` to the `ga()` fuction in `train_GA()`
Additionally, the message `"Running Genetic Algorithm"` can be printed to `stderr` using `message()`, which will get rid of the `[1]` character at the beginning of the message.
A similar behaviour can be achieved with `cat()`, but sending the output to `stdout`. Mind you that `cat()` requires to add newline character at the end `\n`

**Comment by annajenul** [comment]
Thank you very much for the comment! We included a "verbose" parameter in the train function and used message() to print the "Running Genetic Algorithm" as suggested.
