### ISSUE TITLE
Handling of missing data is not stated

### ISSUE THREAD

**Issue by dhvalden** [annajenul/UBayFS#25]
Adding random `NA`s into the training does not throw error nor warnings, but the output changes considerably and some metrics (e.g. `avg feature correlation`) are no longer computed. I believe is necessary to state how the `NA`s are handled and/or do not allow `NA` in the training dataset. Whatever is the path to follow, a transparent handling of the `NA`s is needed.

**Comment by annajenul** [comment]
Thank you for pointing out this issue. We added a warning when the data contains missing values.
