### ISSUE TITLE
Mathematical notation

### ISSUE THREAD

**Issue by osorensen** [annajenul/UBayFS#28]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/4848).

In this equation, there appears to be a small typo. Shouldn't the dot "." be placed after the equation, and not after \kappa(t) (highlighted=?

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/21175639/213394190-c13e9b9b-f337-4294-8565-9453d7c1ef1b.png">

Secondly, I'm not familiar with the notation used in the rightmost part of this equation. Does 
<img width="147" alt="image" src="https://user-images.githubusercontent.com/21175639/213394434-d6010718-db01-477a-99e6-12ee38efc5bd.png">
mean "maximize the thing to the right with respect to delta, subject to delta in [0, 1]^N"?

If so, could you please add a sentence clarifying this?

**Comment by annajenul** [comment]
Thank you, good point. We rewrote the formulas and solved the issue with the "."

**Comment by osorensen** [comment]
Thanks, that was much clearer!
